version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bio.terra:datarepo-client
    versions:
    - 1.0.200-SNAPSHOT
    - 1.0.201-SNAPSHOT
    - 1.11.0-SNAPSHOT
    - 1.12.0-SNAPSHOT
    - 1.13.0-SNAPSHOT
    - 1.14.0-SNAPSHOT
    - 1.15.0-SNAPSHOT
    - 1.17.0-SNAPSHOT
    - 1.18.0-SNAPSHOT
    - 1.21.0-SNAPSHOT
    - 1.26.0-SNAPSHOT
    - 1.28.0-SNAPSHOT
    - 1.3.0-SNAPSHOT
    - 1.31.0-SNAPSHOT
    - 1.32.0-SNAPSHOT
    - 1.35.0-SNAPSHOT
    - 1.36.0-SNAPSHOT
    - 1.38.0-SNAPSHOT
    - 1.39.0-SNAPSHOT
    - 1.4.0-SNAPSHOT
    - 1.40.0-SNAPSHOT
    - 1.41.0-SNAPSHOT
    - 1.42.0-SNAPSHOT
    - 1.43.0-SNAPSHOT
    - 1.44.0-SNAPSHOT
    - 1.46.0-SNAPSHOT
    - 1.48.0-SNAPSHOT
    - 1.49.0-SNAPSHOT
    - 1.50.0-SNAPSHOT
    - 1.51.0-SNAPSHOT
    - 1.52.0-SNAPSHOT
    - 1.56.0-SNAPSHOT
    - 1.58.0-SNAPSHOT
    - 1.62.0-SNAPSHOT
    - 1.64.0-SNAPSHOT
    - 1.65.0-SNAPSHOT
  - dependency-name: com.google.cloud:google-cloud-storage
    versions:
    - 1.113.10
    - 1.113.11
    - 1.113.12
    - 1.113.13
    - 1.113.14
    - 1.113.15
    - 1.113.9
  - dependency-name: com.github.spotbugs
    versions:
    - 4.6.0
    - 4.6.2
    - 4.7.0
  - dependency-name: com.google.oauth-client:google-oauth-client-jetty
    versions:
    - 1.31.4
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
