before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/google-cloud-sdk/

env:
  - PATH=${HOME}/google-cloud-sdk/bin:$PATH CLOUDSDK_CORE_DISABLE_PROMPTS=1

install: gradle wrapper --gradle-version 4.10.2

language: java

jdk:
  - openjdk8

services:
  - docker

before_install:
  - if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud config set project broad-jade-dd
  - ./render-configs.sh $TRAVIS_TOKEN
  - gcloud auth activate-service-account --key-file /tmp/jade-dev-account.pem
  - gcloud auth list
  - ls -la

script:
  - ./gradlew :assemble
  - ./gradlew --console=verbose --info :check --scan
